name: Docker Build And Push

on:
  merge_group:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "renovate/**"
  pull_request:
    paths-ignore:
      - "**/renovate.json"
    branches:
      - "main"
      - "renovate/**"
  schedule:
    - cron: "27 2 * * 1"

env:
  REGISTRY_IMAGE: yfhme/openssl-docker
  TEST_TAG: yfhme/openssl-docker:test

jobs:
  build:
    name: Docker Build And Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=schedule,pattern=weekly
            type=semver,pattern={{raw}}
            type=edge,branch=dev

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Login to Docker Hub
        #if: (github.event_name == 'push') || (gihub.ref == '/refs/head/dev')
        if: github.event.ref_type == 'tag' || github.event.ref_type == 'schedule'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker for test
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test container
        run: |
          docker run --rm ${{ env.TEST_TAG }} bin/openssl version -a

      - name: Build and push
        #if: github.event_name != 'pull_request'
        if: github.event.ref_type == 'tag' || github.event.ref_type == 'schedule'
        id: build
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
