name: Docker Build And Push

on:
  merge_group:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "renovate/**"
  pull_request:
    paths-ignore:
      - "**/renovate.json"
    branches:
      - "main"
      - "renovate/**"
  schedule:
    - cron: "27 2 * * 1"

env:
  REGISTRY_IMAGE: yfhme/openssl-docker
  TEST_TAG: yfhme/openssl-docker:test

jobs:
  build:
    name: Docker Build And Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=schedule,pattern=weekly
            type=semver,pattern={{raw}}
            type=edge,branch=dev

      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0

      - name: Login to Docker Hub
        #if: (github.event_name == 'push') || (gihub.ref == '/refs/head/dev')
        #if: github.event.ref_type == 'tag' || github.event.ref_type == 'schedule'
        if: ${{ github.event.ref_type == 'tag' }} || ${{ github.event_name == 'schedule' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker for test
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6.14.0
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test container
        run: |
          docker run --rm ${{ env.TEST_TAG }} bin/openssl version -a

      - name: Build and push
        #if: github.event_name != 'pull_request'
        if: ${{ github.event.ref_type == 'tag' }} || ${{ github.event_name == 'schedule' }}
        id: build
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6.14.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
