name: Docker Build And Push

on:
  merge_group:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "renovate/**"
  pull_request:
    paths-ignore:
      - "**/renovate.json"
    branches:
      - "main"
      - "renovate/**"
  schedule:
    - cron: "27 2 * * 1"

env:
  REGISTRY_IMAGE: yfhme/openssl-docker
  TEST_TAG: yfhme/openssl-docker:test

jobs:
  build:
    name: Docker Build And Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5.5.0
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=schedule,pattern=weekly
            type=semver,pattern={{raw}}
            type=edge,branch=dev

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Login to Docker Hub
        #if: (github.event_name == 'push') || (gihub.ref == '/refs/head/dev')
        if: github.event.ref_type == 'tag'|| 'schedule'
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker for test
        uses: docker/build-push-action@f6010ea70151369b06f0194be1051fbbdff851b2 # v6.0.2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test container
        run: |
          docker run --rm ${{ env.TEST_TAG }} bin/openssl version -a

      - name: Build and push
        #if: github.event_name != 'pull_request'
        if: github.event.ref_type == 'tag' || 'schedule'
        id: build
        uses: docker/build-push-action@f6010ea70151369b06f0194be1051fbbdff851b2 # v6.0.2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
